language: node_js
# env: 'postgresql://coder:1234@localhost:5432/reg_num'

node_js:
  - "8.9.4"

sudo: false
dist: trusty
addons:
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
  postgresql: 10
env:
  global:
    - PGPORT=5433

  before_script:
  - psql -c 'create database travis;' -U postgres
  - psql -c 'create database reg_num;' -U postgres
  - psql -c "ALTER USER travis WITH PASSWORD 'travis';
  - psql -c '\i registration_table.sql;' -U postgres
  - node ./registration_numbers.js -d postgresql://coder:1234@localhost:5432/reg_num

# language: node_js
# env:
#      'postgresql://coder:1234@localhost:5432/reg_num'
# node_js:
#   - "8.9.4"
#
#   before_script:
#   - psql -c 'create database travis;' -U postgres
#   - psql -c 'create database reg_num;' -U postgres
#   - psql -c "CREATE USER coder WITH PASSWORD 'coder123';" -U postgres
#   - psql -c '\i registration_table.sql;' -U postgres
#   - node ./registration_numbers.js -d postgresql://coder:1234@localhost:5432/reg_num
#
# addons:
#     apt:
#     packages:
#     - postgresql-server-dev-9.2
