language: node_js
# env:
#      'postgresql://coder:1234@localhost:5432/reg_num'
node_js:
  - "8.9.4"

  before_script:
  - psql -c 'create database travis;' -U postgres
  - psql -c 'create database registrations;' -U postgres
  psql -c "CREATE USER coder WITH PASSWORD 'coder123';" -U postgres
  - psql -c '\i registrationdb-script.sql;' -U postgres
  - node ./Registration_Numbers.js -d coder://coder123@localhost:5432/registrations

addons:
    apt:
    packages:
    - postgresql-server-dev-9.2
